version: "3.0"


services:
  trio:
    image: philhawthorne/docker-influxdb-grafana:latest
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
    volumes:
      - ./TESTING/influx:/var/lib/influxdb
      - ./TESTING/grafana:/var/lib/grafana